/*
 * QNode Configuration Header
 * Generated by CMake for MSVC compatibility
 */

#ifndef QNODE_CONFIG_H
#define QNODE_CONFIG_H

/* Platform detection */
#ifdef _WIN32
#define _WIN32_WINNT 0x0601  /* Windows 7 or later */
#endif

/* MSVC compatibility */
#ifdef _MSC_VER
#include "msvc_compat.h"

/* MSVC specific warnings suppression */
#pragma warning(disable: 4244)  /* Conversion from 'type1' to 'type2' */
#pragma warning(disable: 4267)  /* Conversion from 'size_t' to 'type' */
#pragma warning(disable: 4996)  /* Deprecated functions */
#pragma warning(disable: 4200)  /* Zero-sized array */
#pragma warning(disable: 4013)  /* Implicit function declaration */
#pragma warning(disable: 4115)  /* Named type definition in parentheses */

/* MSVC specific definitions */
#define inline __inline
#define __inline__ __inline
#define __func__ __FUNCTION__

#endif /* _MSC_VER */

/* Feature flags */
#define CONFIG_VERSION "1.0.0"
//#define USE_WORKER 1

#endif /* QNODE_CONFIG_H */
